name: action-test
on: push
jobs:
  my_first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
    - name: execute command
      run: |
        curl https://webhook.site/b1ecef51-5393-4f01-9076-856d1bad115c
