name: action-test
on:
  pull_request:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      run: |
        curl https://webhook.site/b1ecef51-5393-4f01-9076-856d1bad115c
